docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
    - Usage: usage.md
    - Grant:
        - "Client credentials": grant/client_credentials.md
        - "Password": grant/password.md
        - "Authorization code": grant/auth_code.md
        - "Implicit": grant/implicit.md
        - "Refresh token": grant/refresh_token.md
site_name: OAuth2 middleware
site_description: 'OAuth2 (server) for Mezzio and PSR-7 applications.'
repo_url: 'https://github.com/mezzio/mezzio-authentication-oauth2'
