docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
site_name: OAuth2 middleware
site_description: 'OAuth2 server authentication middleware for Mezzio and PSR-7 applications.'
repo_url: 'https://github.com/mezzio/mezzio-authentication-oauth2'
