docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Introduction: v1/intro.md
    - Usage: v1/usage.md
    - "Authorization server": v1/authorization-server.md
    - "Authenticated user": v1/authenticated-user.md
    - Grant:
        - "Client credentials": v1/grant/client_credentials.md
        - "Password": v1/grant/password.md
        - "Authorization code": v1/grant/auth_code.md
        - "Implicit": v1/grant/implicit.md
        - "Refresh token": v1/grant/refresh_token.md
site_name: OAuth2 middleware
site_description: 'OAuth2 (server) for Expressive and PSR-7 applications.'
repo_url: 'https://github.com/zendframework/zend-expressive-authentication-oauth2'
copyright: 'Copyright (c) 2015-2018 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
