docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - Introduction: intro.md
site_name: OAuth2 authentication middleware
site_description: 'OAuth2 middleware for Expressive and PSR-7 applications'
repo_url: 'https://github.com/zendframework/zend-expressive-authentication-oauth2'
copyright: 'Copyright (c) 2017 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
